from __future__ import annotations

import numpy as np
import pandas as pd


def prompt_spread(curve: pd.DataFrame) -> float:
    """M1 minus M3. Positive value often indicates prompt tightness in energy markets."""
    if len(curve) < 3:
        return float("nan")
    return float(curve["futures_price"].iloc[0] - curve["futures_price"].iloc[2])


def annualized_carry(curve: pd.DataFrame) -> float:
    """Annualized M1-M12 carry based on futures price ratio."""
    if len(curve) < 2:
        return float("nan")
    f1 = float(curve["futures_price"].iloc[0])
    f_last = float(curve["futures_price"].iloc[-1])
    t_last = float(curve["T"].iloc[-1])
    return (f_last / f1) ** (1 / t_last) - 1


def curve_tightness_score(curve: pd.DataFrame) -> dict:
    """
    Simple explanatory score. Positive = tighter prompt market, negative = more contango/carry.
    It is designed as a monitoring indicator, not as a trading recommendation.
    """
    ps = prompt_spread(curve)
    carry = annualized_carry(curve)
    m1 = float(curve["futures_price"].iloc[0])
    norm_prompt = ps / m1 if m1 else 0.0
    score = 100 * (0.7 * norm_prompt - 0.3 * carry)
    label = "Tight prompt market" if score > 1 else "Carry / loose prompt market" if score < -1 else "Balanced curve"
    return {"prompt_spread": ps, "annualized_carry": carry, "tightness_score": score, "tightness_label": label}


def scenario_library(commodity: str, exposure_units: float, reference_price: float) -> pd.DataFrame:
    """Commodity-specific stress scenarios with simple P&L impact."""
    generic = [
        ("Demand shock", -0.08, "Macro slowdown or weaker industrial/refining demand"),
        ("Supply disruption", 0.12, "Unexpected outage, geopolitical disruption or logistics constraint"),
        ("Inventory build", -0.06, "Inventory accumulation signals easier prompt availability"),
        ("Inventory draw", 0.07, "Drawdown signals stronger prompt demand or supply tightness"),
    ]
    if "Natural Gas" in commodity:
        generic += [
            ("Warm winter", -0.18, "Lower heating demand and storage pressure"),
            ("Cold snap", 0.25, "Weather-driven demand spike and storage withdrawal risk"),
        ]
    elif "Crude" in commodity or "WTI" in commodity:
        generic += [
            ("OPEC+ surprise cut", 0.15, "Policy-driven crude supply reduction"),
            ("Refinery maintenance", -0.10, "Lower crude intake during maintenance season"),
        ]
    elif "Copper" in commodity:
        generic += [
            ("China stimulus", 0.10, "Higher expected industrial and infrastructure demand"),
            ("Mine disruption", 0.12, "Supply shock from strikes, weather or permitting"),
        ]
    elif "Gold" in commodity:
        generic += [
            ("Real rates higher", -0.08, "Higher opportunity cost for holding gold"),
            ("Risk-off move", 0.09, "Safe-haven demand shock"),
        ]
    rows = []
    for name, shock, rationale in generic:
        new_price = reference_price * (1 + shock)
        pnl = exposure_units * (new_price - reference_price)
        rows.append({
            "scenario": name,
            "shock": shock,
            "new_price": new_price,
            "pnl_usd": pnl,
            "rationale": rationale,
        })
    return pd.DataFrame(rows)


def pnl_attribution(exposure_units: float, spot_price: float, curve: pd.DataFrame, hedge_contract: str, contract_size: int, contracts: int) -> pd.DataFrame:
    """Simple desk-style P&L attribution under a stylized 1-day move."""
    hedge_price = float(curve.loc[curve["contract"] == hedge_contract, "futures_price"].iloc[0])
    shock_spot = 0.01
    m1_roll = float(curve["roll_yield_to_next"].iloc[0]) if "roll_yield_to_next" in curve else 0.0
    spot_move = exposure_units * spot_price * shock_spot
    roll_component = exposure_units * hedge_price * (0 if np.isnan(m1_roll) else -m1_roll / 21)
    hedge_component = -(contracts * contract_size * hedge_price * shock_spot)
    residual = spot_move + roll_component + hedge_component
    return pd.DataFrame([
        {"component": "Spot move", "pnl_usd": spot_move, "explanation": "Impact of a +1% move in the underlying commodity price."},
        {"component": "Curve roll", "pnl_usd": roll_component, "explanation": "Approximate daily roll contribution from the front of the curve."},
        {"component": "Futures hedge", "pnl_usd": hedge_component, "explanation": "Offset generated by the futures hedge position."},
        {"component": "Net residual", "pnl_usd": residual, "explanation": "Remaining exposure after hedge and curve effects."},
    ])
